name: 'Terraform installer'
description: 'Install a specific version of terraform binary.'
author: 'Petri Autero'
inputs:
  terraform-version:
    description: 'Terraform version to install'
    required: false
  terraform-version-file:
    description: 'File containing the Terraform version to install.  Examples: .terraform-version'
    required: false
outputs:
  terraform-path:
    description: 'Path to the terraform binary'
branding:
  icon: cloud
  color: 'orange'
runs:
  using: 'node20'
  main: 'lib/index.js'
